name: Regenerate Rotations

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Regenerate Rotations
      run: ./.github/regenerate_rotations.sh
